package com.zkpt.data.entity;

import java.io.Serializable;

public class AuthorizationArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mid_authorization_area.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mid_authorization_area.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mid_authorization_area.USER_CODE
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mid_authorization_area.IS_EFFECT
     *
     * @mbggenerated
     */
    private String isEffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mid_authorization_area.ID
     *
     * @return the value of mid_authorization_area.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mid_authorization_area.ID
     *
     * @param id the value for mid_authorization_area.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mid_authorization_area.NAME
     *
     * @return the value of mid_authorization_area.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mid_authorization_area.NAME
     *
     * @param name the value for mid_authorization_area.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mid_authorization_area.USER_CODE
     *
     * @return the value of mid_authorization_area.USER_CODE
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mid_authorization_area.USER_CODE
     *
     * @param userCode the value for mid_authorization_area.USER_CODE
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mid_authorization_area.IS_EFFECT
     *
     * @return the value of mid_authorization_area.IS_EFFECT
     *
     * @mbggenerated
     */
    public String getIsEffect() {
        return isEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mid_authorization_area.IS_EFFECT
     *
     * @param isEffect the value for mid_authorization_area.IS_EFFECT
     *
     * @mbggenerated
     */
    public void setIsEffect(String isEffect) {
        this.isEffect = isEffect == null ? null : isEffect.trim();
    }
}