#==================== 中间件 == ==============================
middleware:
  server:
    bank:
      ip: 192.168.43.103
      port: 60001
      bufferSize: 2048
      idleTime: 10
      loggerFilterName: logger
      referenceCountingFilterName: myIoFilter
      protocolCodecFilterName: coderc
      charSetName: gbk
    ftp:
      ip: 192.168.43.103
      port: 21
      user: root
      pwd: 123456
      workpath:       
  client:
    gas:
      ip: 192.168.43.103
      port: 10002
      connectTimeoutMillis: 20000
      readBufferSize: 1024
      both_idle: 10
      reader_idle: 15
      writer_idle: 15
      loggerFilterName: logger
      referenceCountingFilterName: myIoFilter
      protocolCodecFilterName: coderc
      charSetName: gbk
    ftp:
      ip: 192.168.43.103
      port: 21
      user: root
      pwd: 123456
      workpath:
  bank:
    newCode: '0008'
    oldCode: '0009'
  ledger:
    charSetName: gbk
    downloadPath: c:/Downloads/
    defaultFileExtensionName: .txt
    ledgerNameBank: DZMX.
    ledgerNameGas: _DZYY_
  maxSessionSize: 100 # 最大IP连接数
  lockedIp: false  # 是否锁定一个IP只能一个连接
  
#==================== 银行测试客户端 ==========================
test:
  client:
    bank:
      connectTimeoutMillis: 5000
      loggerFilterName: logger
      referenceCountingFilterName: myIoFilter
      protocolCodecFilterName: coderc
      charSetName: gbk