package com.zkpt.data.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;

import com.zkpt.data.entity.AuthorizationArea;

@Mapper
public interface AuthorizationAreaMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(AuthorizationArea record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    int insertSelective(AuthorizationArea record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    AuthorizationArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthorizationArea record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_authorization_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthorizationArea record);

    /**
     * @Title:查询所有生效的地区
     * @return
     */
    List<AuthorizationArea> findAllEffect();
}
