package com.zkpt.data.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;
import com.zkpt.data.entity.GasUserBehavior;
import com.zkpt.data.view.StreamView;
import com.zkpt.data.view.UserPaymentView;

@Mapper
public interface GasUserBehaviorMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_gas_user_behavior
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(GasUserBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int insertSelective(GasUserBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_gas_user_behavior
     *
     * @mbggenerated
     */
    GasUserBehavior selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GasUserBehavior record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table mid_gas_user_behavior
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GasUserBehavior record);

    /**
     * 
     * @param UserNo
     * @return
     */
    Page<UserPaymentView> findUserAllPayment(@Param("userNo") String userNo);

    /**
     * 
     * @param streamView
     * @return
     */
    Page<StreamView> findAllStream(StreamView streamView);

    /**
     * 
     * @return
     */
    List<GasUserBehavior> findAllYesterdayStream();
}
