package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;

import com.github.pagehelper.Page;
import com.zkpt.data.entity.GasUser;
import com.zkpt.data.view.UserView;

@Mapper
public interface GasUserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(GasUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int insertSelective(GasUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    GasUser selectByPrimaryKey(Integer id);

    /**
     * 按用户编号查询
     * 
     * @param userNo 用户编码
     * @return
     */
    GasUser selectByUserNo(String userNo);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GasUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_gas_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GasUser record);

    /**
     * 
     * @param userView
     * @return
     */
    Page<UserView> selectAll(UserView userView);
}
