package com.zkpt.data.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;
import com.zkpt.data.entity.Operation;
import com.zkpt.data.view.OperationView;

@Mapper
public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    Operation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * mid_operation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Operation record);

    /**
     * 
     * @param bankCommand
     * @param startTime
     * @param endTime
     * @return
     */
    Page<OperationView> selectAll(@Param("bankCommand") Integer bankCommand, @Param("startTime") String startTime, @Param("endTime") String endTime);
}
